install.packages('coda.base')
install.packages('remotes')
remotes::install_github('mcomas/coda.count', ref = 'SORT-normal-multinomial')
install.packages('randtoolbox')
install.packages('digest')
install.packages('dirmult')
install.packages('HardyWeinberg')
install.packages('rstan')
install.packages('ggtern')